### ISSUE TITLE
Class loading error on server launch

### ISSUE THREAD

**Issue by RJO-Jorn** [ErdbeerbaerLP/ErdbeerbaerGuiLib#108]
Ive been trying to launch a forge server (1.16.5) from my main device with a modpack which includes this mod, everytime when i boot up the server i get this error directing me towards this mod.
Ive tried to figure a workaround etc but after 30m i thought it to be a better idea to just ask help here since there is no one who knows the mod better than the mod owner >_>

I hope this crash log gives enhoug info to locate and find a solustion for this problem.
If more info is needed on this error, feel free to request such.
[crash-2022-08-03_00.38.53-fml.txt](https://github.com/ErdbeerbaerLP/ErdbeerbaerGuiLib/files/9246152/crash-2022-08-03_00.38.53-fml.txt)

**Comment by ErdbeerbaerLP** [comment]
Solution: do not include this mod on the server side.
It's (currently) client side only. During 1.19 I might do an update adding serverside stuff, too
