### ISSUE TITLE
[1.16.2] NoSuchFieldError

### ISSUE THREAD

**Issue by Charismara** [ErdbeerbaerLP/ErdbeerbaerGuiLib#3]
Minecraft: 1.16.2
Forge: 33.0.32
Mappings: 20200820-1.16.1
Crash: [https://pastebin.com/mRGEs2ka](https://pastebin.com/mRGEs2ka)

Beim Klicken in der Modliste crasht das Spiel da das Feld field_230693_o_ welches in MixinModListScreen#onUpdate aufgerufen wird nicht existiert.

**Comment by ErdbeerbaerLP** [comment]
Sollte mit der Version 1.0.4 wieder gehen

(hab vergessen, die issues zu schließen)
