### ISSUE TITLE
eguilib-1.0.3-1.16 crashes forge

### ISSUE THREAD

**Issue by Tigre2000** [ErdbeerbaerLP/ErdbeerbaerGuiLib#5]
I am running 1.16.2 and have Forge forge-1.16.2-33.0.61 installed.  When I put eguilib in the mods folder and run minecraft, it starts OK.  But when I select a world (which I have only one), crashes showing 

2020-09-23 14:47:19,335 main WARN Advanced terminal features are not available in this environment
[32m[14:47:19] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Tiger, --version, 1.16.2-forge-33.0.61, --gameDir, C:\Users\Tiger\AppData\Roaming\.minecraft\Forge1.16.2, --assetsDir, C:\Users\Tiger\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, cd889844badb3b12a292c12c37a2bb2d, --accessToken, ????????, --userType, legacy, --versionType, release, --width, 1600, --height, 900, --launchTarget, fmlclient, --fml.forgeVersion, 33.0.61, --fml.mcVersion, 1.16.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200812.004259]
[m[32m[14:47:19] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 7.0.1+78+master.e9771d8 starting: java version 1.8.0_251 by Oracle Corporation
[m[32m[14:47:19] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m[32m[14:47:19] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Tiger/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=CLIENT
[m[32m[14:47:21] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [de.erdbeerbaerlp.guilib.GuiLibMixinConnector]
[m[32m[14:47:21] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.2-forge-33.0.61, --gameDir, C:\Users\Tiger\AppData\Roaming\.minecraft\Forge1.16.2, --assetsDir, C:\Users\Tiger\AppData\Roaming\.minecraft\assets, --uuid, cd889844badb3b12a292c12c37a2bb2d, --username, Tiger, --assetIndex, 1.16, --accessToken, ????????, --userType, legacy, --versionType, release, --width, 1600, --height, 900]
[m[32m[14:47:25] [Render thread/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[m[32m[14:47:25] [Render thread/INFO] [minecraft/Minecraft]: Setting user: Tiger
[m[32m[14:47:25] [Render thread/INFO] [minecraft/Minecraft]: Backend library: LWJGL version 3.2.2 build 10
[m[32m[14:47:25] [modloading-worker-11/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 33.0.61, for MC 1.16.2 with MCP 20200812.004259
[m[32m[14:47:25] [modloading-worker-11/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v33.0.61 Initialized
[m[32m[14:47:26] [Render thread/INFO] [mojang/NarratorWindows]: Narrator library for x64 successfully loaded
[m[32m[14:47:26] [Render thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, Mod Resources, DragonDance_3
[m[32m[14:47:26] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[m[32m[14:47:27] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: BETA Current: 33.0.61 Target: 33.0.61
[m[32m[14:47:31] [Render thread/INFO] [minecraft/SoundSystem]: OpenAL initialized.
[m[32m[14:47:31] [Render thread/INFO] [minecraft/SoundEngine]: Sound engine started
[m[32m[14:47:31] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 2048x2048x4 minecraft:textures/atlas/blocks.png-atlas
[m[32m[14:47:31] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[m[32m[14:47:31] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[m[32m[14:47:31] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[m[32m[14:47:31] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x4 minecraft:textures/atlas/chest.png-atlas
[m[32m[14:47:31] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[m[32m[14:47:31] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[m[32m[14:47:32] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[m[32m[14:47:32] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[m[32m[14:47:32] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[m[32m[14:47:32] [Realms Notification Availability checker #1/INFO] [mojang/RealmsClient]: Could not authorize you against Realms server: Invalid session id
[m[33m[14:47:37] [Render thread/WARN] [minecraft/MinecraftServer]: Missing data pack mod:torohealth
[m[33m[14:47:37] [Render thread/WARN] [minecraft/MinecraftServer]: Missing data pack mod:xaerominimap
[m[33m[14:47:37] [Render thread/WARN] [minecraft/MinecraftServer]: Missing data pack mod:doubledoors
[m[33m[14:47:37] [Render thread/WARN] [minecraft/MinecraftServer]: Missing data pack mod:collective
[m[33m[14:47:37] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[m[33m[14:47:37] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[m[33m[14:47:37] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[m[33m[14:47:37] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[m[33m[14:47:37] [Render thread/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[m[32m[14:47:37] [Render thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, forge-1.16.2-33.0.61-universal.jar, eguilib-1.0.3-1.16 for MinersAdvantage.jar
[m[32m[14:47:38] [Render thread/INFO] [minecraft/RecipeManager]: Loaded 7 recipes
[m[32m[14:47:38] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 927 advancements
[m[1;31m[14:47:38] [Render thread/ERROR] [ne.mi.fm.FMLWorldPersistenceHook/WP]: This world was saved with mod doubledoors which appears to be missing, things may not work well
[m[1;31m[14:47:38] [Render thread/ERROR] [ne.mi.fm.FMLWorldPersistenceHook/WP]: This world was saved with mod torohealth which appears to be missing, things may not work well
[m[1;31m[14:47:38] [Render thread/ERROR] [ne.mi.fm.FMLWorldPersistenceHook/WP]: This world was saved with mod xaerominimap which appears to be missing, things may not work well
[m[1;31m[14:47:38] [Render thread/ERROR] [ne.mi.fm.FMLWorldPersistenceHook/WP]: This world was saved with mod collective which appears to be missing, things may not work well
[m[32m[14:47:39] [Render thread/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[m[32m[14:47:39] [Server thread/INFO] [minecraft/IntegratedServer]: Starting integrated minecraft server version 1.16.2
[m[32m[14:47:39] [Server thread/INFO] [minecraft/IntegratedServer]: Generating keypair
[m[32m[14:47:39] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
[m[32m[14:47:40] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[14:47:40] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
[m[32m[14:47:40] [Render thread/INFO] [minecraft/LoggingChunkStatusListener]: Time elapsed: 916 ms
[m[1;31m[14:47:40] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.util.ServiceConfigurationError: javax.imageio.spi.ImageInputStreamSpi: Provider com.sun.media.imageioimpl.stream.ChannelImageInputStreamSpi not found
	at java.util.ServiceLoader.fail(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.ServiceLoader.access$300(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.ServiceLoader$LazyIterator.next(Unknown Source) ~[?:1.8.0_251] {}
	at java.util.ServiceLoader$1.next(Unknown Source) ~[?:1.8.0_251] {}
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(Unknown Source) ~[?:1.8.0_251] {}
	at javax.imageio.spi.IIORegistry.<init>(Unknown Source) ~[?:1.8.0_251] {}
	at javax.imageio.spi.IIORegistry.getDefaultInstance(Unknown Source) ~[?:1.8.0_251] {}
	at javax.imageio.ImageIO.<clinit>(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraft.server.MinecraftServer.func_184107_a(MinecraftServer.java:742) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}
[mAL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

I have all other mods removed.  I have tried eguilib-1.0.2-1.16 with same results.

**Comment by ErdbeerbaerLP** [comment]
(Forgot to close)
Should be fixed now
