### ISSUE TITLE
Remove MixinBootstrap Dependency

### ISSUE THREAD

**Issue by Nick1st** [ErdbeerbaerLP/ErdbeerbaerGuiLib#8]
Would it be possible to remove MixinBootstrap as an Dependency  on the MC 1.16.2+ files at Curseforge as it's no longer required since Forge 1.16.1-32.0.72+ has Mixin included.

**Comment by ErdbeerbaerLP** [comment]
Oh yeah, forgot to remove it

**Comment by Nick1st** [comment]
No problem

**Comment by ErdbeerbaerLP** [comment]
Done
